name: Continuous Integration Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_PARALLEL: true
  CMAKE_PARALLELISM: 8
  VENV_PATH: .venv
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Run Clang Format
        uses: actions/checkout@v4
        with:
          repository: 'Sarcasm/run-clang-format'
          path: 'run-clang-format'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format build-essential python3-venv
          python3 -m venv $VENV_PATH
          $VENV_PATH/bin/pip install --upgrade pip
          $VENV_PATH/bin/pip install mypy pytest
      - name: Run Clang Format
        run: |
          sed -i '/InsertNewlineAtEOF: true/d' .clang-format
          ./run-clang-format/run-clang-format.py -r src include test

      - name: Run MyPy
        run: |
          export MYPYPATH=$(pwd)/python
          $VENV_PATH/bin/mypy python
          $VENV_PATH/bin/mypy test
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential software-properties-common python3-venv python3-dev
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13
          gcc --version
          python3 -m venv $VENV_PATH
          $VENV_PATH/bin/pip install --upgrade pip
          $VENV_PATH/bin/pip install build pytest wheel setuptools
          mkdir logs

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          [[ "${CMAKE_PARALLEL}" == true ]] && \
          cmake --build build --parallel "${CMAKE_PARALLELISM}" || \
          cmake --build build

      - name: Run CTests
        run: |
          cd build
          ctest --output-on-failure --verbose --output-junit ../logs/ctest-results.xml
          cd -

      - name: Package Python
        run: |
          cp build/pymasm_core* python/pymasm/
          export PYTHONPATH=$(pwd)
          $VENV_PATH/bin/python -m build python --wheel
          $VENV_PATH/bin/pip install python/dist/pymasm-*.whl
      - name: Run PyTests
        run: |
          $VENV_PATH/bin/pytest --junitxml=logs/pytest-results.xml test
      - name: Publish test results
        uses: dorny/test-reporter@v2.1.1
        if: always()
        with:
          name: Catch2 Tests
          path: logs/*.xml
          reporter: java-junit
          fail-on-error: true
