name: Continuous Integration Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_PARALLEL: true
  CMAKE_PARALLELISM: 8
  VENV_PATH: ${{ github.workspace }}/.venv
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Run Clang Format
        uses: actions/checkout@v4
        with:
          repository: 'Sarcasm/run-clang-format'
          path: 'run-clang-format'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format build-essential python3-venv
          python3 -m venv $VENV_PATH
          $VENV_PATH/bin/pip install --upgrade pip
          $VENV_PATH/bin/pip install mypy pytest
      - name: Run Clang Format
        run: |
          sed -i '/InsertNewlineAtEOF: true/d' .clang-format
          ./run-clang-format/run-clang-format.py -r libmasm masm mdb python shared tests tools

      - name: Run MyPy
        run: |
          export MYPYPATH=$(pwd)/python
          $VENV_PATH/bin/mypy python

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential python3-venv python3-dev
          gcc --version
          python3 -m venv $VENV_PATH
          $VENV_PATH/bin/pip install --upgrade pip
          $VENV_PATH/bin/pip install build wheel setuptools
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          [[ "${CMAKE_PARALLEL}" == true ]] && \
          cmake --build build --parallel "${CMAKE_PARALLELISM}" || \
          cmake --build build
      - name: Package Python
        run: |
          cp build/python/pymasm_core* python/pymasm/
          $VENV_PATH/bin/python -m build python --wheel
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
            python/dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          mkdir -p ${{ github.workspace }}/logs
      - name: Run CTests
        run: |
          chmod +x build/tests/masm-tests
          ctest --test-dir build/tests --output-on-failure --verbose --output-junit ${{ github.workspace }}/logs/ctest-results.xml
      - name: Publish test results
        uses: dorny/test-reporter@v2.1.1
        if: always()
        with:
          name: Catch2 Tests
          path: ${{ github.workspace }}/logs/ctest-results.xml
          reporter: java-junit
          fail-on-error: true

  test-python:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv $VENV_PATH
          $VENV_PATH/bin/pip install --upgrade pip
          $VENV_PATH/bin/pip install pytest
          $VENV_PATH/bin/pip install python/dist/pymasm-*.whl
          mkdir -p ${{ github.workspace }}/logs
      - name: Run PyTests
        run: |
          $VENV_PATH/bin/pytest --junitxml=${{ github.workspace }}/logs/pytest-results.xml python/tests
      - name: Publish test results
        uses: dorny/test-reporter@v2.1.1
        if: always()
        with:
          name: PyTest Tests
          path: ${{ github.workspace }}/logs/pytest-results.xml
          reporter: java-junit
          fail-on-error: true
